#!/usr/bin/env php
<?php

use Mk4U\TGram\Config;

if (file_exists('vendor/autoload.php')) {
    require_once 'vendor/autoload.php';
}

// Config
if (file_exists('config.php')) {
    $cfg = require 'config.php';
}

use Mk4U\TGram\Bot;
use Mk4U\TGram\Commands\CallbackCommand;
use Mk4U\TGram\Commands\CliCommand;
use Mk4U\TGram\Commands\CmdCommand;
use Mk4U\TGram\Commands\ConversationCommand;
use Mk4U\TGram\Commands\HandlerCommand;
use Mk4U\TGram\Commands\HookAboutCommand;
use Mk4U\TGram\Commands\HookDeleteCommand;
use Mk4U\TGram\Commands\HookInfoCommand;
use Mk4U\TGram\Commands\HookSetCommand;
use Mk4U\TGram\Commands\InstallCommand;
use Mk4U\TGram\Commands\MiddlewareCommand;
use Mk4U\TGram\Commands\PollCommand;
use Mk4U\TGram\Commands\RegisterCommand;
use Symfony\Component\Console\Application;

if (!empty($cfg)) {
    Config::init($cfg);
}

$app = new Application(Bot::NAME, 'v' . Bot::VERSION);

// ... register commands
$app->addCommand(new InstallCommand());
$app->addCommand(new RegisterCommand());
//webhook
$app->addCommand(new HookSetCommand());
$app->addCommand(new HookDeleteCommand());
$app->addCommand(new HookInfoCommand());
$app->addCommand(new HookAboutCommand());
//dev
if (!strpos(__DIR__, 'vendor')) {
    $app->addCommand(new CliCommand());
}
//telegram
$app->addCommand(new CmdCommand());
$app->addCommand(new CallbackCommand());
$app->addCommand(new ConversationCommand());
$app->addCommand(new HandlerCommand());
$app->addCommand(new MiddlewareCommand());
//polling
$app->addCommand(new PollCommand());

$app->run();
